//
// Created by Angel on 6/7/2026.
//

#ifndef PLANTDYNAMICSSIMULATOR_WEATHERSYSTEM_H
#define PLANTDYNAMICSSIMULATOR_WEATHERSYSTEM_H


class WeatherSystem {
};


#endif //PLANTDYNAMICSSIMULATOR_WEATHERSYSTEM_H